### ISSUE TITLE
[Validator] Doubled places

### ISSUE THREAD

**Issue by Rub21** [osmlab/osmlint#105]
These are places that have been tagged twice, as a polygon and a point.
https://gist.github.com/aaronlidman/50c355e1b3e180115a19#doubled-places

cc. @aaronlidman @planemad @maning

**Comment by aaronlidman** [comment]
This should be easy. Would be a fun onboarding task.

**Comment by samely** [comment]
@Rub21  I've already added this [validator](https://github.com/osmlab/osmlint/tree/doubledplaces).  You can see some outputs for [Peru](https://gist.github.com/samely/04144ccc9788fc643a8efbaaeafb9e3c) and [Italy](https://gist.github.com/samely/af9142b7622967857fb2e6346b2ba452).

**Comment by samely** [comment]
@Rub21 here's the [task](http://osmlab.github.io/to-fix/#/task/doubledplaces)

**Comment by samely** [comment]
@Rub21  I've updated the validator, where I filtered some tags due to as we don't have local knowledge, it's better not to touch them:
- `public_transport=*`
- `railway=*`
- `amenity= bus_station`
- `highway=*`
- `place=*`
- `amenity=parking_entrance`
- `addr:housenumber=*`

You can review all [issues](http://osmlab.github.io/to-fix/#/task/doubledplaces). Maybe there are more tags to filter.

**Comment by samely** [comment]
[here's](https://github.com/osmlab/osmlint/tree/doubledPlaces) the branch

**Comment by samely** [comment]
@Rub21  I've added the test.

**Comment by Rub21** [comment]
@samely  I foud some false positive :

![image](https://cloud.githubusercontent.com/assets/1152236/18328231/9b1652a4-7513-11e6-874f-42016d814e07.png)
https://www.openstreetmap.org/node/3376788044/history
https://www.openstreetmap.org/way/305975672/history

creo que los objetos deben contener almenos dos etiquetas incluyendo el nombre.

**Comment by Rub21** [comment]
@samely : lowercase , uppercase sensibility, we should compare it as well. 

![image](https://cloud.githubusercontent.com/assets/1152236/18328747/d34fb1e0-7515-11e6-81b5-092df9d2244f.png)

**Comment by samely** [comment]
I've updated this validator --> [repo](https://github.com/osmlab/osmlint/tree/doubled)

* Since we don't have a local knowledge for all places I avoid those tags: `public_transport=*`, `railway=*`, `amenity= bus_station`, `highway=*`, `place=*`, `amenity=parking_entrance` and `addr:housenumber=*`

* I also considered doubledPlaces just for: `historic:`, `leisure:`, `landuse:` and `shop:` tags
* I obtained some [issues for Spain](https://gist.github.com/samely/e79c637d329e3964e55d6de9967a2e0f)

**Comment by samely** [comment]
[Done](https://github.com/osmlab/osmlint/pull/192) here.
