### ISSUE TITLE
Validator for invalid highway connections

### ISSUE THREAD

**Issue by MoKob** [osmlab/osmlint#235]
I just fixed a connection from https://www.openstreetmap.org/way/50585885#map=17/38.85814/-77.04637 to https://www.openstreetmap.org/way/50585886#map=19/38.85709/-77.04712
resulting in
![](https://user-images.githubusercontent.com/12932279/27826945-56f81f2e-60b5-11e7-9073-51f8a1a390d6.png).

I am unsure if this could be validated automatically, but it might be possible to detect connections by these via a combination of turn angles, bride tags, z-levels and road classes.

**Comment by daniel-j-h** [comment]
To be clear here (what I didn't see on first sight): the first right turn a bit below the green start marker is a turn onto a bridge and therefore upwards by some meters. Someone accidentally connected the two ways.

**Comment by srividyacb** [comment]
Really nice catch 👍  @daniel-j-h @MoKob 

We should be detecting a `layer=*` road forming a junction with the highway running underneath which is not having a layer tag. Also any layered highways should never make ^^ junctions. 

cc @Rub21

**Comment by Rub21** [comment]
@MoKob @daniel-j-h @srividyacb : I am looking two issues here:

- The motorway  and the bridge were connected in a node, that was fixed by  Mokob in the [changeset](https://www.openstreetmap.org/changeset/50031136)

- It is missing `layer:*` in the bridge.

We already have the validator to detect these issues: [mixedLayer](https://github.com/osmlab/osmlint/blob/master/validators/mixedLayer/map.js). we can create run it for the planet and then create a to-fix task to start fixing it. 

cc. @calfarome @dannykath

**Comment by daniel-j-h** [comment]
Great! Fixing these is critical for our routing engine.

Imaging the in-car device telling you to turn upwards onto a bridge ;-)

**Comment by Rub21** [comment]
@daniel-j-h Due to `mixedLayer`validator detect all issues that have intersected between different layers. `layer=*` but not an intersection between bridges and highways, for that reason I  created a new validator to detect highways and bridges that intersect in a node, `crossing highways and bridges` https://github.com/osmlab/osmlint/issues/238, and also I create a task in to-fix :point_down:  for  US detections. 

 https://osmlab.github.io/to-fix/#/task/crossinghighwaysandbridges

**Comment by Rub21** [comment]
We are ready here, closing the ticket.
