### ISSUE TITLE
[Validator] Node ending near other highway

### ISSUE THREAD

**Issue by Rub21** [osmlab/osmlint#45]
cc. @geohacker @batpad @maning

**Comment by Rub21** [comment]
#### Progress: 
- [branch nodeendingnearhighway](https://github.com/osmlab/osmlint/tree/nodeendingnearhighway)
- [result]( https://gist.github.com/anonymous/1e570991a0856ddfa8f9) 
 @maning Can you take a look  on result.

**Comment by Rub21** [comment]
@maning : new result is this: https://gist.github.com/anonymous/6e34347bb93203d7e55f, I've improved to avoid many false positive.

**Comment by maning** [comment]
This is tricky. Notes below:
* How updated is your, test mbtiles? I'm seeing recently fixed nodes ( ~ 2 days ago) that were detected.
* 3.2 meter might be large, I'm seeing false positives beyond 1.2 meters.  Can we decrease the buffer size <= 1 meter and then make it bigger later on if we see false negatives?
* Can we standardize units? I prefer we use SI instead of imperial.

**Comment by Rub21** [comment]
@maning 
> How updated is your, test mbtiles? I'm seeing recently fixed nodes ( ~ 2 days ago) that were detected.

my peru.mbtiles was old, I've updated the latest.

> 3.2 meter might be large, I'm seeing false positives beyond 1.2 meters. Can we decrease the buffer size <= 1 meter and then make it bigger later on if we see false negatives?

I think  2 meter is fine.  in size <=1 many of the errors are avoided. 

> Can we standardize units? I prefer we use SI instead of imperial.

we will use `meters` [units. ](https://github.com/osmlab/osmlint/blob/nodeendingnearhighway/validators/nodeEndingNearHighway/map.js#L25)


new results: https://gist.github.com/anonymous/2308bdc52d1ecf741cba

**Comment by maning** [comment]
@Rub21 results looks OK!

**Comment by Rub21** [comment]
merge on master!
