### ISSUE TITLE
Better code reuse is possible in this project

### ISSUE THREAD

**Issue by d1g** [osmlab/osmlint#60]
I wasn't looking too deep in code/commit history, but I see common validation code I saw in other projects.

I do understand that this project was created around (and probably because of) mbtiles format, but slogan "and to identify common geometry and metadata problems at scale" is quite similar to what https://github.com/osm-fr/osmose-backend did for years (along with other QA tools).

It makes no sense to do same job twice, please reuse existing code or steal ideas (with credit to authors) where possible.

Similar to #9 and #10 I guess.

**Comment by planemad** [comment]
@d1g no doubt there have been numerous attempts at creating QA streams from OSM data, each with its own approach. The design considerations with osmlint are:
- Open source
- Works on [osm qa tiles](http://osmlab.github.io/osm-qa-tiles/) or any other .mbtiles for convenience instead of a database
- Built on [tile-reduce](https://github.com/mapbox/tile-reduce) to make processing extremely fast (<10mins for a global data sweep)
- Easy to use by any mapper to create and try out their own processor

https://github.com/osm-fr/osmose-backend/tree/master/analysers is an amazing resource that can help write more linters. This is not duplication of work because analyzing mbtiles using turf is very different from making spatial queries to a postgis database using python. Hopefully this will become so easy that anyone should be able to write and test their own linter in a matter of minutes.

Thanks for bringing this up, we definitely want to reuse as much as possible all the time, and the logic of osmose analysers will be really handy in the work forward.

**Comment by planemad** [comment]
cc @Rub21 @geohacker @mikelmaron
